export const GridData = [
  {
    make: "Tesla",
    model: "Model Y",
    price: 64950,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-02-15",
  },
  {
    make: "Ford",
    model: "F-Series",
    price: 33850,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2022-10-12",
  },
  {
    make: "Toyota",
    model: "Corolla",
    price: 29600,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-05-20",
  },
  {
    make: "Chevrolet",
    model: "Bolt EV",
    price: 31500,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-01-18",
  },
  {
    make: "BMW",
    model: "i3",
    price: 44450,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2022-11-05",
  },
  {
    make: "Audi",
    model: "Q5",
    price: 43700,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-03-08",
  },
  {
    make: "Hyundai",
    model: "Kona Electric",
    price: 37490,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-06-11",
  },
  {
    make: "Nissan",
    model: "Leaf",
    price: 31600,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-07-02",
  },
  {
    make: "Honda",
    model: "Civic",
    price: 25700,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2022-09-22",
  },
  {
    make: "Mercedes-Benz",
    model: "EQC",
    price: 67000,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-04-14",
  },
  {
    make: "Volkswagen",
    model: "ID.4",
    price: 41500,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-08-21",
  },
  {
    make: "Subaru",
    model: "Outback",
    price: 33295,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-01-30",
  },
  {
    make: "Mazda",
    model: "MX-30",
    price: 34395,
    electric: true,
    performance: { good: false, bad: true, average: false, type: "bad" },
    manufacturingDate: "2023-03-19",
  },
  {
    make: "Rivian",
    model: "R1T",
    price: 73000,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2022-12-07",
  },
  {
    make: "Lucid",
    model: "Air",
    price: 77400,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-05-25",
  },
  {
    make: "Volvo",
    model: "XC40 Recharge",
    price: 53700,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-02-11",
  },
  {
    make: "Porsche",
    model: "Taycan",
    price: 83000,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-06-02",
  },
  {
    make: "Jaguar",
    model: "I-PACE",
    price: 69995,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2022-11-15",
  },
  {
    make: "Kia",
    model: "Niro EV",
    price: 39690,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-09-01",
  },
  {
    make: "Ram",
    model: "1500",
    price: 37590,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2022-10-05",
  },
  {
    make: "GMC",
    model: "Sierra 1500",
    price: 40900,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-07-17",
  },
  {
    make: "Chevrolet",
    model: "Silverado",
    price: 41800,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-04-22",
  },
  {
    make: "Ford",
    model: "Mustang Mach-E",
    price: 42995,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-03-28",
  },
  {
    make: "Tesla",
    model: "Model 3",
    price: 43990,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2022-09-10",
  },
  {
    make: "Jeep",
    model: "Wrangler",
    price: 31995,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-06-30",
  },
  {
    make: "Dodge",
    model: "Charger",
    price: 32995,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-08-07",
  },
  {
    make: "Honda",
    model: "Accord",
    price: 28300,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2022-12-20",
  },
  {
    make: "Toyota",
    model: "Camry",
    price: 28400,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-01-22",
  },
  {
    make: "Hyundai",
    model: "Elantra",
    price: 21700,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-07-10",
  },
  {
    make: "Kia",
    model: "Soul EV",
    price: 33690,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-02-17",
  },
  {
    make: "Volkswagen",
    model: "Passat",
    price: 27995,
    electric: false,
    performance: { good: false, bad: false, average: true, type: "average" },
    manufacturingDate: "2023-05-13",
  },
  {
    make: "Tesla",
    model: "Model S",
    price: 89990,
    electric: true,
    performance: { good: true, bad: false, average: false, type: "good" },
    manufacturingDate: "2023-09-06",
  },
];
